// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: rpcheader.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallSeq uint64 `protobuf:"varint,1,opt,name=callSeq,proto3,oneof" json:"callSeq,omitempty"`
	Method  string `protobuf:"bytes,2,opt,name=method,proto3,oneof" json:"method,omitempty"`
}

func (x *CommHeader) Reset() {
	*x = CommHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcheader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommHeader) ProtoMessage() {}

func (x *CommHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rpcheader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommHeader.ProtoReflect.Descriptor instead.
func (*CommHeader) Descriptor() ([]byte, []int) {
	return file_rpcheader_proto_rawDescGZIP(), []int{0}
}

func (x *CommHeader) GetCallSeq() uint64 {
	if x != nil {
		return x.CallSeq
	}
	return 0
}

func (x *CommHeader) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ReqHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqHeader) Reset() {
	*x = ReqHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcheader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHeader) ProtoMessage() {}

func (x *ReqHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rpcheader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHeader.ProtoReflect.Descriptor instead.
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return file_rpcheader_proto_rawDescGZIP(), []int{1}
}

type RespHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
}

func (x *RespHeader) Reset() {
	*x = RespHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcheader_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespHeader) ProtoMessage() {}

func (x *RespHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rpcheader_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespHeader.ProtoReflect.Descriptor instead.
func (*RespHeader) Descriptor() ([]byte, []int) {
	return file_rpcheader_proto_rawDescGZIP(), []int{2}
}

func (x *RespHeader) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespHeader) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comm       *CommHeader `protobuf:"bytes,1,opt,name=comm,proto3,oneof" json:"comm,omitempty"`
	ReqHeader  *ReqHeader  `protobuf:"bytes,2,opt,name=reqHeader,proto3,oneof" json:"reqHeader,omitempty"`
	RespHeader *RespHeader `protobuf:"bytes,3,opt,name=respHeader,proto3,oneof" json:"respHeader,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcheader_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_rpcheader_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_rpcheader_proto_rawDescGZIP(), []int{3}
}

func (x *Header) GetComm() *CommHeader {
	if x != nil {
		return x.Comm
	}
	return nil
}

func (x *Header) GetReqHeader() *ReqHeader {
	if x != nil {
		return x.ReqHeader
	}
	return nil
}

func (x *Header) GetRespHeader() *RespHeader {
	if x != nil {
		return x.RespHeader
	}
	return nil
}

var File_rpcheader_proto protoreflect.FileDescriptor

var file_rpcheader_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x5f, 0x0a, 0x0a, 0x43, 0x6f, 0x6d,
	0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x53,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x07, 0x63, 0x61, 0x6c, 0x6c,
	0x53, 0x65, 0x71, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x71, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x52, 0x65,
	0x71, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x15,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x06,
	0x0a, 0x04, 0x5f, 0x6d, 0x73, 0x67, 0x22, 0xca, 0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x2b, 0x0a, 0x04, 0x63, 0x6f, 0x6d, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x6d, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x34,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x48, 0x01, 0x52, 0x09, 0x72, 0x65, 0x71, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x02, 0x52, 0x0a,
	0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x65, 0x71, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcheader_proto_rawDescOnce sync.Once
	file_rpcheader_proto_rawDescData = file_rpcheader_proto_rawDesc
)

func file_rpcheader_proto_rawDescGZIP() []byte {
	file_rpcheader_proto_rawDescOnce.Do(func() {
		file_rpcheader_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcheader_proto_rawDescData)
	})
	return file_rpcheader_proto_rawDescData
}

var file_rpcheader_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpcheader_proto_goTypes = []interface{}{
	(*CommHeader)(nil), // 0: models.CommHeader
	(*ReqHeader)(nil),  // 1: models.ReqHeader
	(*RespHeader)(nil), // 2: models.RespHeader
	(*Header)(nil),     // 3: models.Header
}
var file_rpcheader_proto_depIdxs = []int32{
	0, // 0: models.Header.comm:type_name -> models.CommHeader
	1, // 1: models.Header.reqHeader:type_name -> models.ReqHeader
	2, // 2: models.Header.respHeader:type_name -> models.RespHeader
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpcheader_proto_init() }
func file_rpcheader_proto_init() {
	if File_rpcheader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcheader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcheader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcheader_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcheader_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpcheader_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_rpcheader_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_rpcheader_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcheader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpcheader_proto_goTypes,
		DependencyIndexes: file_rpcheader_proto_depIdxs,
		MessageInfos:      file_rpcheader_proto_msgTypes,
	}.Build()
	File_rpcheader_proto = out.File
	file_rpcheader_proto_rawDesc = nil
	file_rpcheader_proto_goTypes = nil
	file_rpcheader_proto_depIdxs = nil
}
